package controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import model.InHouse;
import model.Inventory;
import model.Outsourced;
import model.Part;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.Scanner;

/**
 * The controller for interaction between Part.java and AddPart.fxml
 *
 * @author Blake Ramsey
 */
public class AddPart implements Initializable{

    public Button addPartCancelButton;
    public TextField addPartIdTxt;
    public TextField addPartNameTxt;
    public TextField addPartInventoryTxt;
    public TextField addPartCostTxt;
    public TextField addPartMaxTxt;
    public TextField addPartVariableTxt;
    public TextField addPartMinTxt;
    public RadioButton addPartInHouseRB;
    public RadioButton addPartOutSourcedRB;
    public Button addPartSaveBtn;
    public Label inHouseVSOutsourcedLabel;

    private String name;
    private int id;

    /**
     * This method initializes the AddPart controller after root element has been processed.
     *
     * @param url Resolves relative paths for root object, or null if location is not known.
     * <br>
     * @param resourceBundle Resources used to localize root object, or null if root object was not localized.
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
    }

    /**
     * This method directs user to the next appropriate window.<br><br> LOGICAL ERROR - Corrected order of width and height
     * as the windows that were initialized after method was called were the wrong proportion.
     *
     * @param fxmlDoc The location of the window that should be loaded.
     * @param buttonClicked The button that is clicked.
     * @param width The width of window to be loaded.
     * @param height The height of window to be loaded.
     * @throws IOException
     */
    private void windowLoader (String fxmlDoc, Button buttonClicked, double width, double height) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(AddPart.class.getResource(fxmlDoc.toString()));
        Scene scene = new Scene(fxmlLoader.load(), width, height);
        Stage stage = (Stage) buttonClicked.getScene().getWindow();
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method invokes windowloader method in order to direct user back to previous screen.
     *
     * @param actionEvent The actionEvent generated by Cancel button being clicked.
     * @throws IOException
     */
    public void onCancelClick (ActionEvent actionEvent) throws IOException {
        windowLoader("/view/main-window.fxml", addPartCancelButton, 1000, 400);
    }

    /**
     * This method take information from text fields and generates a new part, with appropriate exceptions being
     * thrown when fields are filled in incorrectly. This method invokes windowloader method in order to return
     * to previous window.<br><br> RUNTIME ERROR - Added 'Integer.parseInt' to get inventory amount, my first attempt was trying
     * assign a String to an int variable.
     *
     * @param actionEvent The actionEvent generated by Save button being clicked.
     * @throws IOException
     */
    public void onSaveButtonClick(ActionEvent actionEvent) throws IOException {
        try {
            if (!Inventory.getAllParts().isEmpty()) {
                Part part = Inventory.getAllParts().get((Inventory.getAllParts().size() - 1));
                int tempID = part.getId();
                id = tempID + 1;
            } else {
                id = 1;
            }

            String name = addPartNameTxt.getText();
            if (name.isEmpty()) {
                throw new Exception("Part must have name");
            }
            int inventory = Integer.parseInt(addPartInventoryTxt.getText());
            double cost = Double.parseDouble(addPartCostTxt.getText());
            int max = Integer.parseInt(addPartMaxTxt.getText());
            int min = Integer.parseInt(addPartMinTxt.getText());

            if (min >= max) {
                throw new Exception("Min should be less than Max.");
            }
            if ((inventory > max) || (inventory < min)) {
                throw new Exception("Inventory must be between Min and Max");
            }

            if (addPartInHouseRB.isSelected()) {
                int machineID = Integer.parseInt(addPartVariableTxt.getText());
                InHouse newPart = new InHouse(id, name, cost, inventory, min, max, machineID);
                Inventory.addPart(newPart);
            } else {
                String companyName = addPartVariableTxt.getText();
                Outsourced newPart = new Outsourced(id, name, cost, inventory, min, max, companyName);
                Inventory.addPart(newPart);
            }

            windowLoader("/view/main-window.fxml", addPartCancelButton, 1000, 400);
        }
        catch(NumberFormatException nfe) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText("Please enter a valid value for each text field.");
            alert.showAndWait();
        }
        catch(Exception e) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText(e.getMessage());
            alert.showAndWait();

        }
    }

    /**
     * This method sets label text to reflect Radio Button selected.
     *
     * @param actionEvent This actionEvent is generated by Outsourced RadioButton being clicked.
     */
    public void onOutsourced(ActionEvent actionEvent) {
        inHouseVSOutsourcedLabel.setText("Company Name");
    }

    /**
     * This method sets label text to reflect Radio Button selected.
     *
     * @param actionEvent This actionEvent is generated by InHouse RadioButton being clicked.
     */
    public void onInHouse(ActionEvent actionEvent) {
        inHouseVSOutsourcedLabel.setText("Machine ID");
    }
}
