package controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import model.InHouse;
import model.Inventory;
import model.Outsourced;
import model.Part;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.Scanner;

/**
 * The controller for interaction between Part.java and ModifyPart.fxml
 *
 * @author Blake Ramsey
 */
public class ModifyPart implements Initializable {

    public Button modifyPartCancelButton;
    public RadioButton modifyPartInHouseRB;
    public RadioButton modifyPartOutsourcedRB;
    public Button modifyPartSaveBtn;
    public TextField modifyPartIdTxt;
    public TextField modifyPartNameTxt;
    public TextField modifyPartInventoryTxt;
    public TextField modifyPartCostTxt;
    public TextField modifyPartMaxTxt;
    public TextField modifyPartMinTxt;
    public ToggleGroup modifyPart;

    public static Part modifiedPart;
    public TextField modifyPartVariableTxt;
    public Label modPartVariableLabel;

    /**
     * This method initializes the AddProduct controller after root element has been processed.
     *
     * @param url Resolves relative paths for root object, or null if location is not known.
     *
     * @param resourceBundle Resources used to localize root object, or null if root object was not localized.
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        if (modifiedPart instanceof InHouse) {
            modifyPartInHouseRB.setSelected(true);
            modifyPartVariableTxt.setText(Integer.toString(((InHouse) modifiedPart).getMachineId()));
            modPartVariableLabel.setText("Machine ID");
        }
        else {
            modifyPartOutsourcedRB.setSelected(true);
            Outsourced outsourcedPart = (Outsourced)modifiedPart;
            modifyPartVariableTxt.setText(outsourcedPart.getCompanyName());
            modPartVariableLabel.setText("Company Name");

        }
        modifyPartIdTxt.setText(Integer.toString(modifiedPart.getId()));
        modifyPartNameTxt.setText(modifiedPart.getName());
        modifyPartInventoryTxt.setText(Integer.toString(modifiedPart.getStock()));
        modifyPartCostTxt.setText(Double.toString(modifiedPart.getPrice()));
        modifyPartMaxTxt.setText(Integer.toString(modifiedPart.getMax()));
        modifyPartMinTxt.setText(Integer.toString(modifiedPart.getMin()));
    }

    /**
     * This method directs user to the next appropriate window.<br><br> LOGICAL ERROR - Deleted redundant ActionEvent field, as
     * 'buttonClicked' Button was already performing the same duty.
     *
     * @param fxmlDoc The location of the window that should be loaded.
     * @param buttonClicked The button that is clicked.
     * @param width The width of window to be loaded.
     * @param height The height of window to be loaded.
     * @throws IOException
     */
    public void windowLoader (String fxmlDoc, Button buttonClicked, double width, double height) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(ModifyPart.class.getResource(fxmlDoc.toString()));
        Scene scene = new Scene(fxmlLoader.load(), width, height);
        Stage stage = (Stage) buttonClicked.getScene().getWindow();
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method invokes windowloader method in order to direct user back to previous screen.
     *
     * @param actionEvent The actionEvent generated by Cancel button being clicked.
     * @throws IOException
     */
    public void onCancelClick(ActionEvent actionEvent) throws IOException {
        windowLoader("/view/main-window.fxml", modifyPartCancelButton, 1000, 400);
    }


    /**
     * This method take information from text fields and generates a new part in the corrected index, with appropriate exceptions being
     * thrown when fields are filled in incorrectly. This method invokes windowloader method in order to return
     * to previous window.
     *
     * @param actionEvent The actionEvent generated by Save button being clicked.
     * @throws IOException
     */
    public void onSaveButtonClick(ActionEvent actionEvent) throws IOException {
        Part partToMod;
        int indexOfPart;
        try {

            indexOfPart = Inventory.getAllParts().indexOf(modifiedPart);
            int id = modifiedPart.getId();
            String name = modifyPartNameTxt.getText();
            if (name.isEmpty()) {
                throw new Exception("Part must have name");
            }
            int stock = Integer.parseInt(modifyPartInventoryTxt.getText());
            double price = Double.parseDouble(modifyPartCostTxt.getText());
            int max = Integer.parseInt(modifyPartMaxTxt.getText());
            int min = Integer.parseInt(modifyPartMinTxt.getText());

            if (min >= max) {
                throw new Exception("Min must be less than max");
            }
            if (stock < min || stock > max) {
                throw new Exception("Inventory must be between min and max");
            }
            if (modifyPartInHouseRB.isSelected()) {
                int machineID = Integer.parseInt(modifyPartVariableTxt.getText());
                partToMod = new InHouse(id, name, price, stock, min, max, machineID);
                Inventory.updatePart(indexOfPart, partToMod);
            }
            else if (modifyPartOutsourcedRB.isSelected()) {
                String companyName = modifyPartVariableTxt.getText();
                partToMod = new Outsourced(id, name, price, stock, min, max, companyName);
                Inventory.updatePart(indexOfPart, partToMod);
            }
            windowLoader("/view/main-window.fxml", modifyPartSaveBtn, 1000, 400);
        }
        catch (NumberFormatException nfe) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText("Please enter a valid value for each text field");
            alert.showAndWait();
        }
        catch (Exception e) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText(e.getMessage());
            alert.showAndWait();
        }

    }

    /**
     * This method sets label text to reflect Radio Button selected.
     *
     * @param actionEvent This actionEvent is generated by Outsourced RadioButton being clicked.
     */
    public void onModOutsourcedBtnClick(ActionEvent actionEvent) {
        modPartVariableLabel.setText("Company Name");
    }

    /**
     * This method sets label text to reflect Radio Button selected.
     *
     * @param actionEvent This actionEvent is generated by InHouse RadioButton being clicked.
     */
    public void onModInHouseBtnClick(ActionEvent actionEvent) {
        modPartVariableLabel.setText("Machine ID");
    }
}
